### ISSUE TITLE
Download link for icons missing

### ISSUE THREAD

**Issue by Ashvith10** [ByteSeb/Duel#1]
There isn't any source for the icons used at [21:33](https://youtu.be/WtvObZHhdf0?t=1293)  (Importing links). It would be helpful if you could share it.

**Comment by Ashvith10** [comment]
Perhaps this is what people coming from the video might be looking for? - [Download link for icons folder](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FByteSeb%2FDuel%2Ftree%2Fmain%2Fsrc%2Ficons)

**Comment by byteseb** [comment]
Thanks for the issue. Yes, I'll add it to the video's description and Readme file.
